baseurl: ""
url: ""
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: blog/:title

postcss:
  cache: false

plugins:
  - jekyll-postcss

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
