title: Kadafi's Portfolio
tagline: Personal Portfolio 
description: My personal portfolio contains my career journey and projects that have been carried out
author: Muhamad Rizki Kadafi
logo: /assets/image/favicon.png
social:
  name: Muhamad Rizki Kadafi
  links:
    - https://www.linkedin.com/in/rizkikadafi 
    - https://github.com/rizkikadafi
baseurl: ""
url: ""

postcss:
  cache: false

plugins:
  - jekyll-postcss

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
